Added measuring solving time.
JonathanSalwan/Triton pull request #1064
Opened 2021-12-24 14:53 UTC by kobrineli

Added measuring solving time to switch between inputs in FuzzBench depending on summary solving time.

2021-12-24 15:12 UTC, SweetVishnya requested changes

2021-12-24 15:12 UTC, SweetVishnya commented on src/libtriton/api/api.cpp
>    }
isSat function + docs

2021-12-24 15:12 UTC, SweetVishnya commented on src/libtriton/engines/solver/z3/z3Solver.cpp
> +            *solving_time = (std::chrono::duration_cast<std::chrono::milliseconds>(end - start)).count();
redundant parentheses

2021-12-24 15:39 UTC, kobrineli commented on src/libtriton/api/api.cpp
>    }
Done

2021-12-24 15:39 UTC, kobrineli commented on src/libtriton/engines/solver/z3/z3Solver.cpp
> +            *solving_time = (std::chrono::duration_cast<std::chrono::milliseconds>(end - start)).count();
Done

2021-12-24 16:18 UTC, JonathanSalwan commented
Can you also update the Python Bindings and add an unit test?

2021-12-26 09:36 UTC, JonathanSalwan commented on src/libtriton/api/api.cpp
> +  std::unordered_map<triton::usize, triton::engines::solver::SolverModel> API::getModel(const triton::ast::SharedAbstractNode& node, triton::engines::solver::status_e* status, triton::uint32 timeout,
Can you replace all `triton::uint32 *var_name` by `triton::uint32* var_name`? The pointer keyword (`*`) must be attached to its type in matter of following the coding style :)

2022-01-02 13:16 UTC, merged

2022-01-02 13:38 UTC, SweetVishnya commented
AFAIK, @kobrineli was working on Python bindings and tests. Anyway, @JonathanSalwan you may (or not) add them as you wish. Moreover, we should mind the same parameter for Bitwuzla in #1062

2022-01-02 13:43 UTC, JonathanSalwan commented
Mmmh, as i got no answer I'm currently deving the Python bindings but if he's working on it i will let him finish :)

2022-01-02 13:46 UTC, SweetVishnya commented
If you are already working, then you would make it faster. @kobrineli is on his exams and won't be able to commit soon.

P.S. We should speak up plans on our side in future)))

2022-01-02 14:13 UTC, JonathanSalwan commented
> If you are already working, then you would make it faster. @kobrineli is on his exams and won't be able to commit soon.

Ok I can do that :). Good luck to him for his exams.

> P.S. We should speak up plans on our side in future)))

Yeah, because I see an army of the ISP RAS guys committing on Triton :)